### ISSUE TITLE
NoSuchElementException in MimeType

### ISSUE THREAD

**Issue by eroux** [dbmdz/digitalcollections-core#1]
I'm using these classes from iiif-apis, but there seems to be some errors in the mime file parsing. Here is a code to reproduce the problem (I don't actually use it, I copied it from iiif-apis):

```java
    @Test
    public void testMime() {
        System.out.println(MimeType.fromTypename("image/jpeg"));
    }
```

part of the `pom.xml`:

```xml
        <dependency>
            <groupId>de.digitalcollections.iiif</groupId>
            <artifactId>iiif-apis</artifactId>
            <version>0.3.0</version>
        </dependency>
```

and the stacktrace:

```txt
java.lang.ExceptionInInitializerError
	at io.bdrc.iiif.presentation.PresentationTest.testMime(PresentationTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.util.NoSuchElementException
	at com.google.common.base.AbstractIterator.next(AbstractIterator.java:79)
	at de.digitalcollections.core.model.api.MimeType.lambda$static$1(MimeType.java:39)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at de.digitalcollections.core.model.api.MimeType.<clinit>(MimeType.java:40)
	... 24 more
```

how can I solve this?

**Comment by jbaiter** [comment]
Can you check the Guava version on your class path? We're using 23.0.
My best guess is that you're on a version that does not have this fix: https://github.com/google/guava/commit/55524c66de8db4c2e44727b69421c7d0e4f30be0

> Before this fix, splitting a single character input string with a
Splitter.onPattern instance created with a zero-width regex pattern,
would have caused the input string to be dropped from the output,
resulting in an empty iterable being returned rather than a single
element one.

The line referenced in your stack trace calls `Splitter.on` and the Exception being thrown is what one would expect if the Iterator returned by `.split(l).iterator()` were empty:

```java
    List<String> typeStrings = mimeReader.lines()
        .map(l -> l.replaceAll("^# ", ""))
        .filter(l -> MIME_PATTERN.matcher(Splitter.on('\t').trimResults().omitEmptyStrings().split(l).iterator().next()).matches())
        .collect(Collectors.toList());
```

**Comment by eroux** [comment]
I have:

```
$mvn dependency:tree |grep guava
[INFO] |  +- com.google.guava:guava:jar:23.0:compile

```

but the problem is more with the path to `mimes.type`, if I copy it to the `src/main/resources/` of my project, everything works. Not sure what the best way to handle this is...

**Comment by jbaiter** [comment]
Hm, that really shouldn't be necessary oO
Can you maybe provide a minimal setup along with a pom.xml that exhibits the behavior? That might help me pin down the cause, since I can't currently reproduce this locally.

**Comment by eroux** [comment]
If you run the junit test `testMime()` of [this project](https://github.com/BuddhistDigitalResourceCenter/buda-iiif-presentation) it should be apparent. The project is not really minimal, but the test is straightforward.

**Comment by jbaiter** [comment]
Okay, I found the cause:

- In your dependencies you have `com.amazonaws:aws-java-sdk` which has a `mime.types` in its resource root
- `de.digitalcollections.core:dc-core-model` ships its own `mime.types` in its resource root
- Since the dependencies are loaded in lexicographical order the AWS resource takes precedence over the dc-core resource with the same name
- The `mime.types` in AWS differs from the one that is expected, revealing a bug in the parsing code

I'll fix the parsing bug and make sure that the expected `mime.types` is not overridden by other packages.

**Comment by eroux** [comment]
I see! Thanks a lot

**Comment by jbaiter** [comment]
I just pushed a new 2.0.3 release that incorporates the fixes.

**Comment by eroux** [comment]
very cool, thanks a lot!
